version: '2'
services:
  db:
    container_name: db
    image: couchbase
    ports:
      - 8091-8096:8091-8096
      - 11210:11210
    environment:
      NODE_TYPE: DEFAULT
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: todoadmin
      CLUSTER_NAME: My Couchbase Cluster
      SERVICES: data,index,query,fts
      CLUSTER_RAMSIZE: 500
      BUCKET: todo
      BUCKET_RAMSIZE: 300
      ENABLE_FLUSH: 1
      SAMPLE_BUCKETS: beer-sample,travel-sample
    volumes:
      - ./couchbase/db:/opt/couchbase/var
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - TODO_CB_CONNECTIONSTRING=couchbase://db